[package]
name = "medea-turn-bin"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "Lightweight STUN/TURN server implementation."
authors = ["Instrumentisto Team <developer@instrumentisto.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
publish = false

[dependencies]
clap = { version = "4.0", features = ["derive"], default-featurs = false }
medea-turn = { path = ".." }
serde = { version = "1.0", features = ["derive"], default-featurs = false }
tokio = { version = "1.46", features = ["macros", "signal"], default-featurs = false }
toml = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"], default-featurs = false }
