[package]
name = "medea-turn-bin"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "Lightweight STUN/TURN server implementation."
authors = ["Instrumentisto Team <developer@instrumentisto.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
publish = false

[dependencies]
anyhow = "1.0"
config = { version = "0.15", features = ["toml"], default-features = false }
dotenvy = "0.15"
medea-turn = { path = ".." }
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = "1.0"
smart-default = "0.7"
time = { version = "0.3", features = ["formatting"],  default-features = false }
tokio = { version = "1.46", features = ["macros", "signal"], default-features = false }
tracing = "0.1"
tracing-core = "0.1"
tracing-log = "0.2"
tracing-record-hierarchical = "0.1"
tracing-serde = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"], default-features = false }
